// GENERATED CODE - DO NOT MODIFY BY HAND
// (Generated by 'scripts/generate-inputs.ts')
import * as core from '@actions/core'

const keys: [key: string, required: boolean][] = [
  ['id', true],
  ['number', true],
  ['message', false],
  ['config', false],
  ['force-checked', false],
  ['body', true],
  ['token', true],
]

export type Inputs = {
  id: string
  number: string
  message: string | null
  config: string | null
  'force-checked': string | null
  body: string
  token: string
}

export const getInputs = (): Inputs => {
  const inputs = Object.create(null)
  for (const [key, required] of keys) {
    const v = core.getInput(key, { required })
    inputs[key] = !required && v === '' ? null : v
  }
  return inputs as Inputs
}
